### ISSUE TITLE
Edit <head> section.

### ISSUE THREAD

**Issue by juhacz** [witsec/mobirise-code-editor#2]
Is it possible to edit the <head> section, e.g. to add js files?

**Comment by gunnarhaslinger** [comment]
for inserting Code into the `<head>` Section you use the "Page Name" Extension, not the "Code Editor".
See: https://witsec.nl/extension-page-name.html

**Comment by juhacz** [comment]
Thank You for geat work!

**Comment by witsec** [comment]
Thanks, @gunnarhaslinger, for helping out, much appreciated!

Hope you got it all figured out, @juhacz.
